### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaImages/ImageInTerminal.jl#65]
```colorview(RGB, rand(3, 10, 10))```

produce nice image

<img width="663" alt="Screen Shot 2022-03-31 at 5 47 52 PM" src="https://user-images.githubusercontent.com/5632376/161167444-657e03cb-9cce-497a-ad41-5fc2d113c12f.png">

however,

```colorview(RGB, rand(3, 100, 100))```

produces very blurred image:

<img width="823" alt="Screen Shot 2022-03-31 at 5 49 16 PM" src="https://user-images.githubusercontent.com/5632376/161167585-eaee3ba4-fd43-40b3-87ad-0207b8ad3e82.png">

Is there workaround?!

**Comment by johnnychen94** [comment]
This is deliberate: when you print a 10x10 small image, you can perfectly fit each row in your terminal, but that case changes when it becomes to 100x100 or larger. For this reason ImageInTerminal internally downsampled the image until it fits the screen https://github.com/JuliaImages/ImageInTerminal.jl/blob/03b1c0fb56a44037a35ed107df1bf971fffb15b4/src/encodeimg.jl#L48-L51 Because you use random image here so you observed severe blurry effect.

You can pass `maxsize` to `imshow`, e.g.:

```julia
img = rand(RGB, 100, 100)
imshow(img, size(img))
```

but I think that looks worse.
